apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service-deployment
  labels:
    app: auth-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
      - name: auth-service
        imagePullPolicy: IfNotPresent
        image: segment17hub/authservice:0.1.5
        ports:
        - containerPort: 50051
        env:
          - name: AUTH_MYSQL_SERVICE_ADDR
            value: "auth-mysql-service"
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
  labels:
    app: auth-service
spec:
  type: ClusterIP
  selector:
    app: auth-service
  ports:
    - name: grpc
      port: 50051
      targetPort: 50051
---
# MYSQL
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-mysql-deployment
spec:
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:5.6
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: root
        volumeMounts:
          - name: auth-mysql-persistent-storage
            mountPath: /var/lib/mysql
      volumes:
        - name: auth-mysql-persistent-storage
          persistentVolumeClaim:
            claimName: auth-mysql-volume-claim
---
apiVersion: v1
kind: Service
metadata:
  name: auth-mysql-service
spec:
  selector:
    app: mysql
  ports:
    - port: 3306
      targetPort: 3306
  type: ClusterIP
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: auth-mysql-volume-claim
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: getambassador.io/v2
kind: Mapping 
metadata:
  name: auth-service
spec:
  grpc: True
  prefix: /ubc_package.AuthService/
  rewrite: /ubc_package.AuthService/
  service: auth-service:50051
  timeout_ms: 4000
  idle_timeout_ms: 500000
  connect_timeout_ms: 2000
---
