apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
      - name: auth-service
        imagePullPolicy: Never
        image: segment17/authservice
        ports:
        - containerPort: 50051
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  type: ClusterIP
  selector:
    app: auth-service
  ports:
    - name: grpc
      port: 50051
      targetPort: 50051
---
# MYSQL
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-mysql-deployment
spec:
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:5.7
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: root
        volumeMounts:
          - name: auth-mysql-persistent-storage
            mountPath: /var/lib/mysql
      volumes:
        - name: auth-mysql-persistent-storage
          persistentVolumeClaim:
            claimName: auth-mysql-claim
---
apiVersion: v1
kind: Service
metadata:
  name: auth-mysql-service
spec:
  selector:
    app: mysql
  ports:
    - port: 3306
      targetPort: 3306
  type: ClusterIP
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: auth-mysql-claim
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
# MYSQL